# Generated by Django 4.2.6 on 2023-10-10 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer', models.IntegerField()),
                ('banks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bank')),
                ('paypals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paypal')),
            ],
        ),
    ]
