# Generated by Django 4.2.6 on 2023-10-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_bank_balance_alter_paypal_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='balance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paypal',
            name='balance',
            field=models.IntegerField(),
        ),
    ]
